CloudSave/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from cloud_azure import urls as azure_urls
from base import  urls as base_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'azure/', include(azure_urls,namespace='azure')),
    path(r'', include(base_urls, namespace='base')),
]

base/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
app_name = "instances"
urlpatterns = [
    # path("", views.index, name='index'),
    path("", views.index, name='home' ),
]

cloud_azure/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = "instances"
urlpatterns = [
    # path("", views.index, name='index'),
    path("home/", views.index, name='home'),
    path("azure/", views.azure, name='azure'),
    path("vm/deallocated/<str:timefilter>", views.getDeallocatedInstances,name='deallocated'),
    path("vm/deallocated/", views.getDeallocatedInstances,name='deallocated'),
    # path("vms2/", views.vms2,name='vms2'),
    path("disks/", views.index, name='disks'),
    path("blob/", views.index, name='blob'),
    # path("collect/", views.collectVmsFromAzure,name='collect'),
    path("vm/tags/", views.tags, name='tags'),
    path("vm/tags/<str:timefilter>", views.tags, name='tags'),
    # path("tags/",views.getTags, name='tags')
    # path("vm/deallocated", views.deallocated, name='deallocated'),
    path("backup/", views.backup,name = 'backup'),
]

cloud_azure/models.py
from django.db import models

# Create your models here.

azure/views.py
from django.shortcuts import render
from pymongo import MongoClient
from src.azure import Azclass as az
import threading, time, os, datetime
from src.azuresdk import AzureSdk as azsdk
title = "Azuremon"
az_appid = os.environ['AZ_APPID']
az_dn = os.environ['AZ_DISPLAYNAME']
az_name = os.environ['AZ_NAME']
az_passwd = os.environ['AZ_PASSWD']
az_tenant = os.environ['AZ_TENANT']
az_subscription = os.environ['AZ_SUBSCRIPTION']
mongoserver = os.environ['MONGOSERVER']
mongodb = os.environ['MONGODB']
menu = {}
menu = {
    "home": "HOME",
    "vms": "Virtual Machines",
    "disks": "Disks",
    "blob":  "Blob",
    "collect": "Collect data"}
now = datetime.datetime.now().strftime("%Y%m%d%H%M%S")

def index(request):
    return render(request, 'index.html', {"active":"home","menu": menu,'title':title, 'data':now})
def getDeallocatedInstances(request):
    mongocollection = "vms"
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db[mongocollection]
    vms = collection.find({ "displayStatus": {"$ne": "VM running"}})
    vmsdealoc = vms.count()
    vmstotal = collection.find().count()
    return  render(request, 'instances.html',{"active":"vms","menu": menu,'title':title, 'vms':vms,"statistic":{"vmsdealoc":vmsdealoc, "vmstotal":vmstotal}})
def collectVmsFromAzure(request):
    # print("thread")
    t = threading.Thread(target=collectVmsFromAzureThread2)
    t.start()
    # while t.is_alive():
    #     print("Thread rodando")
    #     time.sleep(5)
    return render(request, 'index.html', {"active": "collect", "menu": menu, 'title': title})
def collectVmsFromAzureThread():
    print("thread Start")

    nuvem = az(az_appid, az_dn, az_name, az_passwd, az_tenant, az_subscription)
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db['vms']
    print("Drop collection vms in " + mongodb + " database")
    collection.drop()
    retorno = nuvem.getVmsList()
    for data in retorno:
        try:
            print("Collecting vms in " + mongodb + " database")
            LOG_id = collection.insert_one(data)
        except ValueError:
            print("Fail to write data to database.")
        else:
            print(LOG_id)
def collectVmsFromAzureThread2():
    print("thread Start")
    # nuvem = az(az_appid, az_dn, az_name, az_passwd, az_tenant, az_subscription)
    azure = azsdk(az_appid,az_dn,az_name,az_passwd,az_tenant,az_subscription)
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db['vms']
    print("Drop collection vms in " + mongodb + " database")
    vmlist = azure.getAllVms()
    print(vmlist)
    return False
    # collection.drop()
    # retorno = nuvem.getVmsList()
    # for data in retorno:
    #     try:
    #         print("Collecting vms in " + mongodb + " database")
    #         LOG_id = collection.insert_one(data)
    #     except ValueError:
    #         print("Fail to write data to database.")
    #     else:
    #         print(LOG_id)
def getTags(request):
    nuvem = az(az_appid, az_dn, az_name,az_passwd,az_tenant,az_subscription)
    nuvem.getVmsList()
    return render(request, 'azure_tags.html',{})
def vms2(request):
    mongocollection = "vms"
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db[mongocollection]
    vms = collection.find({ "displayStatus": {"$ne": "VM running"}})
    vmsdealoc = vms.count()
    vmstotal = collection.find().count()
    return  render(request, 'instances.html',{"active":"vms","menu": menu,'title':title, 'vms':vms,"statistic":{"vmsdealoc":vmsdealoc, "vmstotal":vmstotal}})
    # return render(request,'azure_vms2.html',{})

cloud_azure/views.py
from django.shortcuts import render
from pymongo import MongoClient
# from src.azure import Azclass as az
from src.azuresdk import Azclass as az
import threading, time, os, datetime
from src.azuresdk import AzureSdk as azsdk

title = "CloudSave Framework"
az_appid = os.environ['AZ_APPID']
az_dn = os.environ['AZ_DISPLAYNAME']
az_name = os.environ['AZ_NAME']
az_passwd = os.environ['AZ_PASSWD']
az_tenant = os.environ['AZ_TENANT']
az_subscription = os.environ['AZ_SUBSCRIPTION']
mongoserver = os.environ['MONGOSERVER']
mongodb = os.environ['MONGODB']
menu = {}
menu = {
    "home": "HOME",
    "vms": "Virtual Machines",
    "disks": "Disks",
    "blob": "Blob",
    "collect": "Collect data"}
now = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
now_human = datetime.datetime.strptime(now, "%Y%m%d%H%M%S")
cloud_azure = azsdk(az_appid,az_dn,az_name,az_passwd,az_tenant,az_subscription)
# cloud_azure.login()

def index(request):
    return render(request, 'index.html', {"active": "home", "menu": menu, 'title': title, 'data': now})


def azure(request):
    return render(request, 'azure.html',
                  {"active": "home", "menu": menu, 'title': title, 'date': now, "datehuman": now_human})


def tags(request, timefilter="last"):
    mongocollection = "vms"
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db[mongocollection]
    try:
        col_datetimes = collection.find().distinct("datetime")
        datearray = []
        datearraycounter = 1
        for date in col_datetimes:
            array = []
            array.append(str(datetime.datetime.strptime(date, "%Y%m%d%H%M%S")))
            array.append(datearraycounter)
            array.append(date)
            datearray.append(array)
            datearraycounter = datearraycounter + 1
            print(date)
            print(str(datetime.datetime.strptime(date, "%Y%m%d%H%M%S")))

        if timefilter == "last":
            print("last")
            vms = collection.find({"datetime": max(col_datetimes)})
            col_datetime_human = datetime.datetime.strptime(max(col_datetimes), "%Y%m%d%H%M%S")


        else:
            print(timefilter)
            col_datetime_human = datetime.datetime.strptime(timefilter, "%Y%m%d%H%M%S")
            vms = collection.find({"datetime": timefilter})
            # datearray = False
        # col_datetime = collection.distinct("datetime")

    except ValueError as err:
        print(err)
    array = []
    for vm in vms:
        if "billing" not in vm["tags"]:
            # print(vm["tags"])
            array.append(vm)
    # print(len(array))
    return render(request, 'no_tags.html',
                  {"data": array, "now": now, "COUNT": len(array), "TOTAL": vms.count(), "WHEM": col_datetime_human,
                   'title': title, "DATEARRAY": datearray})


def deallocated(request):
    mongocollection = "vms"
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db[mongocollection]
    try:
        col_datetimes = collection.find().distinct("datetime")
        vms = collection.find({"datetime": max(col_datetimes)})
    except ValueError as err:
        print(err)
    array = []
    for vm in vms:
        if "billing" not in vm["tags"]:
            array.append(vm)
    col_datetime_human = datetime.datetime.strptime(max(col_datetimes), "%Y%m%d%H%M%S")
    datearray = []
    datearraycounter = 1
    for date in col_datetimes:
        array = []
        array.append(str(datetime.datetime.strptime(date, "%Y%m%d%H%M%S")))
        array.append(datearraycounter)
        array.append(date)
        datearray.append(array)
        datearraycounter = datearraycounter + 1
        print(date)
        print(str(datetime.datetime.strptime(date, "%Y%m%d%H%M%S")))
    return render(request, 'deallocated.html',
                  {"active": "home", "menu": menu, 'title': title, 'date': now, "datehuman": now_human,
                   "DATEARRAY": datearray})


def getDeallocatedInstances(request, timefilter="last"):
    # mongocollection = "vms"
    # client = MongoClient(mongoserver)
    # db = client[mongodb]
    # collection = db[mongocollection]
    # vms = collection.find({"state": {"$ne": "PowerState/running"}})
    # for vm in vms:
    #     print(vm)
    # vmsdealoc = vms.count()
    # print(vmsdealoc)
    # vmstotal = collection.find().count()
    # return render(request, 'deallocated.html', {"active": "vms", "menu": menu, 'title': title, 'vms': vms,
    #                                           "statistic": {"vmsdealoc": vmsdealoc, "vmstotal": vmstotal}})
    mongocollection = "vms"
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db[mongocollection]
    try:
        col_datetimes = collection.find().distinct("datetime")
        datearray = []
        datearraycounter = 1
        for date in col_datetimes:
            array = []
            array.append(str(datetime.datetime.strptime(date, "%Y%m%d%H%M%S")))
            array.append(datearraycounter)
            array.append(date)
            datearray.append(array)
            datearraycounter = datearraycounter + 1
            print(date)
            print(str(datetime.datetime.strptime(date, "%Y%m%d%H%M%S")))

        if timefilter == "last":
            print("last")
            vms = collection.find({"state": {"$ne": "PowerState/running"},"datetime": max(col_datetimes)})
            # vms = collection.find({"datetime": max(col_datetimes)})
            col_datetime_human = datetime.datetime.strptime(max(col_datetimes), "%Y%m%d%H%M%S")


        else:
            print(timefilter)
            col_datetime_human = datetime.datetime.strptime(timefilter, "%Y%m%d%H%M%S")
            vms = collection.find({"datetime": timefilter,"state": {"$ne": "PowerState/running"}})
            # vms = collection.find({"datetime": timefilter})
            # datearray = False
        # col_datetime = collection.distinct("datetime")

    except ValueError as err:
        print(err)
    # vmsdealoc = vms.count()
    # array = []
    # for vm in vms:
    #     if "billing" not in vm["tags"]:
    #         # print(vm["tags"])
    #         array.append(vm)
    # print(len(array))
    print(vms)
    return render(request, 'deallocated.html',
                  { "now": now, "TOTAL": vms.count(), "WHEM": col_datetime_human,
                   'title': title, "DATEARRAY": datearray, "vms":vms.sort("statetime")})
    # return render(request, 'no_tags.html',
    #               {"data": array, "now": now, "COUNT": len(array), "TOTAL": vms.count(), "WHEM": col_datetime_human,
    #                'title': title, "DATEARRAY": datearray})

#
# def getTags(request):
#     nuvem = az(az_appid, az_dn, az_name,az_passwd,az_tenant,az_subscription)
#     nuvem.getVmsList()
#     return render(request, 'azure_tags.html',{})
# def vms2(request):
#     mongocollection = "vms"
#     client = MongoClient(mongoserver)
#     db = client[mongodb]
#     collection = db[mongocollection]
#     vms = collection.find({"displayStatus": {"$ne": "VM running"}})
#     vmsdealoc = vms.count()
#     vmstotal = collection.find().count()
#     return render(request, 'instances.html', {"active": "vms", "menu": menu, 'title': title, 'vms': vms,
#                                               "statistic": {"vmsdealoc": vmsdealoc, "vmstotal": vmstotal}})
#     return render(request,'azure_vms2.html',{})
#

def backup(request):
    protecteds = cloud_azure.getBackupProtectedItems()
    return render(request, 'backup.html', {'title': title, 'protecteds':protecteds})

cloud_azure/templates/azure.html
{% extends "base.html" %}
{% block base %}
    <nav class="navbar navbar-expand-sm  navbar-light" style="background-color: #e3f2fd;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item ">
{#                    <a class="nav-link" href="{% url 'azure:azure' %}">Disks</a>#}
                    <a class="nav-item nav-link disabled" href="#" data-toggle="tooltip" data-placement="top" title="Not Available" >Disks</a>
                </li>

                <li class="nav-item ">
{#                    <a class="nav-link" href="{% url 'azure:azure' %}">BLOB</a>#}
                    <a class="nav-item nav-link disabled" href="#" data-toggle="tooltip" data-placement="top" title="Not Available" >BLOB</a>
                </li>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'azure:tags' %}">TAG Billing</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'azure:deallocated' %}">Deallocated VMS</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'azure:backup' %}">Backup(Protected Items)</a>
                </li>

            </ul>
        </div>
    </nav>
    {#{{ date }} <br>#}
    {#    {{ datehuman }}#}
{% endblock %}
{% block azure %}
{% endblock %}

cloud_azure/templates/azure_tags.html
{% extends "base.html" %}
{% block base %}
    azure_tags
{% endblock %}

cloud_azure/templates/azure_vms2.html
{% extends "base.html" %}
{% block base %}
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th>name</th>
        <th>resource</th>
        <th>vmSize</th>
      <th>location</th>
      <th>time</th>
      <th>code</th>
      <th>displayStatus</th>

    </tr>
  </thead>
  <tbody>
{% for vm in vms %}

    <tr>
    <td >{{vm.name}}</td>
        <td >{{vm.resource}}</td>
        <td >{{vm.vmSize}}</td>
        <td >{{vm.location}}</td>
        <td >{{vm.time}}</td>
        <td >{{vm.code}}</td>
        <td >{{vm.displayStatus}}</td>
  </tr>
    {% endfor %}
  </tbody>
</table>
<center>
Deallocated / Total VMS <br>
{{ statistic.vmsdealoc }} / {{ statistic.vmstotal }}
{% endblock %}

cloud_azure/templates/backup.html
{% extends "azure.html" %}
{% block azure %}
        <br>

    <center>
        <h3>Servers within a backup policy.</h3><br>
    </center> <br>
    <table class="table table-hover" style="font-size: small">
        <thead class="thead-dark">
        <tr>
            <th>Vault Resource Group</th>
            <th>vault Name</th>
            <th>protectionContainers</th>
            <th>protectedItems</th>
            <th>subscription</th>
        </tr>
        </thead>
        {% for item in protecteds %}
            <tr>
                <th style="width: 16.66%">{{ item.rg }}</th>
                <th>{{ item.vault }}</th>
                <th>{{ item.protectionContainers }}</th>
                <th>{{ item.protectedItems }}</th>
                <th>{{ item.subscription }}</th>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

cloud_azure/templates/deallocated.html
{% extends "azure.html" %}
{% block azure %}
    <br>

    <center>
        <h3>Deallocated Virtual Machines</h3><br>
        Total <br>
        {{ TOTAL }} <br>
        Query from : {{ WHEM }}
    </center> <br>
    {#    {% if DATEARRAY == "False" %}#}
    <div class="col">
        <div>
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% for date in DATEARRAY %}
                        <li class="page-item"><a class="page-link" href="{{ date.2 }}" data-toggle="tooltip"
                                                 data-placement="top" title="{{ date.0 }}">{{ date.1 }}</a></li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
    {#    {%  endif %}#}
    <table class="table table-hover" style="font-size: small">
        <thead class="thead-dark">
        <tr>
            <th>RGNAME</th>
            <th>VMNAME</th>
            <th>LOCATION</th>
            <th>VM SIZE</th>
            <th>IPADDRESS</th>
            <th>DATETIME</th>
        </tr>
        </thead>
        {% for vm in vms %}
            <tr>
            <th>{{ vm.vmname }}</th>
            <th>{{ vm.rgname }}</th>
                <th> {{ vm.location }}</th>
                <th>{{ vm.size }}</th>
                <th>{{ vm.network.ip }}</th>
            <th>{{ vm.statetime }}</th>
            </tr>
        {% endfor %}
    </table>
{#    {% for vm in vms %}#}
{#        {{ vm }} <br>#}
{#    {% endfor %}#}
{% endblock %}

cloud_azure/templates/instances.html
{% extends "base.html" %}
{% block base %}
    <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th>name</th>
            <th>resource</th>
            <th>vmSize</th>
            <th>location</th>
            <th>time</th>
            <th>code</th>
            <th>displayStatus</th>
        </tr>
        </thead>
        <tbody>
        {% for vm in vms %}
            <tr>
                <td>{{ vm.name }}</td>
                <td>{{ vm.resource }}</td>
                <td>{{ vm.vmSize }}</td>
                <td>{{ vm.location }}</td>
                <td>{{ vm.time }}</td>
                <td>{{ vm.code }}</td>
                <td>{{ vm.displayStatus }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <center>
    Deallocated / Total VMS <br>
    {{ statistic.vmsdealoc }} / {{ statistic.vmstotal }}
{% endblock %}

cloud_azure/templates/no_tags.html
{% extends "azure.html" %}
{% block azure %}
    <br>

    <center>
        <h3>Servers without the "Billing" TAG.</h3><br>
        Results / Total <br>
        {{ COUNT }} / {{ TOTAL }} <br>
        Query from : {{ WHEM }}
    </center> <br>
    {#    {% if DATEARRAY == "False" %}#}
    <div class="col">
        <div>
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% for date in DATEARRAY %}
                        <li class="page-item"><a class="page-link" href="{{ date.2 }}" data-toggle="tooltip"
                                                 data-placement="top" title="{{ date.0 }}">{{ date.1 }}</a></li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
    {#    {%  endif %}#}
    <table class="table table-hover" style="font-size: small">
        <thead class="thead-dark">
        <tr>
            <th>RGNAME</th>
            <th>VMNAME</th>
            <th>TAGS</th>
        </tr>
        </thead>
        {% for item in data %}
            <tr>
                <th style="width: 16.66%">{{ item.rgname }}</th>
                <th>{{ item.vmname }}</th>
                {% for tag in tags %}
                    {{ tag }}
                {% endfor %}
                <th>{{ item.tags }}</th>
            </tr>
        {% endfor %}
    </table>

{% endblock %}