CloudSave/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from cloud_azure import urls as azure_urls
from base import  urls as base_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'azure/', include(azure_urls,namespace='azure')),
    path(r'', include(base_urls, namespace='base')),
]

base/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
app_name = "instances"
urlpatterns = [
    # path("", views.index, name='index'),
    path("", views.index, name='home' ),
]

cloud_azure/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = "instances"
urlpatterns = [
    # path("", views.index, name='index'),
    path("home/", views.index, name='home'),
    path("azure/", views.azure, name='azure'),
    path("vm/deallocated/<str:timefilter>", views.getDeallocatedInstances,name='deallocated'),
    path("vm/deallocated/", views.getDeallocatedInstances,name='deallocated'),
    # path("vms2/", views.vms2,name='vms2'),
    path("disks/", views.index, name='disks'),
    path("blob/", views.index, name='blob'),
    # path("collect/", views.collectVmsFromAzure,name='collect'),
    path("vm/tags/", views.tags, name='tags'),
    path("vm/tags/<str:timefilter>", views.tags, name='tags'),
    # path("tags/",views.getTags, name='tags')
    # path("vm/deallocated", views.deallocated, name='deallocated'),
    path("backup/", views.backup,name = 'backup'),
]

azure/views.py
from django.shortcuts import render
from pymongo import MongoClient
from src.azure import Azclass as az
import threading, time, os, datetime
from src.azuresdk import AzureSdk as azsdk
title = "Azuremon"
az_appid = os.environ['AZ_APPID']
az_dn = os.environ['AZ_DISPLAYNAME']
az_name = os.environ['AZ_NAME']
az_passwd = os.environ['AZ_PASSWD']
az_tenant = os.environ['AZ_TENANT']
az_subscription = os.environ['AZ_SUBSCRIPTION']
mongoserver = os.environ['MONGOSERVER']
mongodb = os.environ['MONGODB']
menu = {}
menu = {
    "home": "HOME",
    "vms": "Virtual Machines",
    "disks": "Disks",
    "blob":  "Blob",
    "collect": "Collect data"}
now = datetime.datetime.now().strftime("%Y%m%d%H%M%S")

def index(request):
    return render(request, 'index.html', {"active":"home","menu": menu,'title':title, 'data':now})
def getDeallocatedInstances(request):
    mongocollection = "vms"
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db[mongocollection]
    vms = collection.find({ "displayStatus": {"$ne": "VM running"}})
    vmsdealoc = vms.count()
    vmstotal = collection.find().count()
    return  render(request, 'instances.html',{"active":"vms","menu": menu,'title':title, 'vms':vms,"statistic":{"vmsdealoc":vmsdealoc, "vmstotal":vmstotal}})
def collectVmsFromAzure(request):
    # print("thread")
    t = threading.Thread(target=collectVmsFromAzureThread2)
    t.start()
    # while t.is_alive():
    #     print("Thread rodando")
    #     time.sleep(5)
    return render(request, 'index.html', {"active": "collect", "menu": menu, 'title': title})
def collectVmsFromAzureThread():
    print("thread Start")

    nuvem = az(az_appid, az_dn, az_name, az_passwd, az_tenant, az_subscription)
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db['vms']
    print("Drop collection vms in " + mongodb + " database")
    collection.drop()
    retorno = nuvem.getVmsList()
    for data in retorno:
        try:
            print("Collecting vms in " + mongodb + " database")
            LOG_id = collection.insert_one(data)
        except ValueError:
            print("Fail to write data to database.")
        else:
            print(LOG_id)
def collectVmsFromAzureThread2():
    print("thread Start")
    # nuvem = az(az_appid, az_dn, az_name, az_passwd, az_tenant, az_subscription)
    azure = azsdk(az_appid,az_dn,az_name,az_passwd,az_tenant,az_subscription)
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db['vms']
    print("Drop collection vms in " + mongodb + " database")
    vmlist = azure.getAllVms()
    print(vmlist)
    return False
    # collection.drop()
    # retorno = nuvem.getVmsList()
    # for data in retorno:
    #     try:
    #         print("Collecting vms in " + mongodb + " database")
    #         LOG_id = collection.insert_one(data)
    #     except ValueError:
    #         print("Fail to write data to database.")
    #     else:
    #         print(LOG_id)
def getTags(request):
    nuvem = az(az_appid, az_dn, az_name,az_passwd,az_tenant,az_subscription)
    nuvem.getVmsList()
    return render(request, 'azure_tags.html',{})
def vms2(request):
    mongocollection = "vms"
    client = MongoClient(mongoserver)
    db = client[mongodb]
    collection = db[mongocollection]
    vms = collection.find({ "displayStatus": {"$ne": "VM running"}})
    vmsdealoc = vms.count()
    vmstotal = collection.find().count()
    return  render(request, 'instances.html',{"active":"vms","menu": menu,'title':title, 'vms':vms,"statistic":{"vmsdealoc":vmsdealoc, "vmstotal":vmstotal}})
    # return render(request,'azure_vms2.html',{})

base/views.py
from django.shortcuts import render
import datetime
title = "Azuremon"
menu = {}
menu = {
    "home": "HOME",
    "vms": "Virtual Machines",
    "disks": "Disks",
    "blob":  "Blob",
    "collect": "Collect data"}
now = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
# Create your views here.
def index(request):
    return render(request, 'index.html', {"active":"home","menu": menu,'title':title, 'data':now})

azure/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
  <title>{{title}}</title>
  <!--<link rel="stylesheet" href="{% static 'css/menu.css' %}">-->
</head>

<meta name="viewport" content="width=device-width, initial-scale=1"></meta>
<meta name="mobile-web-app-capable" content="yes">
<meta charset="UTF-8">
<body>
<br>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/limenu.cssbs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">{{title}}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">


{#        {% for key, value in menu.items %}#}
{#      <li class="nav-item active">#}
{#          {% if key == active %}#}
{#          <a class="nav-link" href="/{{ key }}/">{{value}} <span class="sr-only">(current)</span></a>#}
{#          {% else %}#}
{#          <a class="nav-link" href="/{{ key }}/">{{value}}</a>#}
{#          {% endif %}#}
{#      </li>#}
{#        {% endfor %}#}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'azure:home' %}">Azure</a>
      </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'azure:vms' %}">Virtual Machines</a>
      </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'azure:disks' %}">Disks</a>
      </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'azure:blob' %}">BLOB</a>
      </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'azure:collect' %}">collect</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

<!--<img src="/static/images/terry-crews.jpg" height="120" width="320" >-->
<!--<img src="/static/images/terry-crews.jpg" height="120" width="320" >-->
    {% autoescape off %}
        {% block menu %}
        {% endblock %}
        {% block base %}
        {% endblock %}
    {% endautoescape %}

</body>
</html>

azure/templates/index.html
{% extends "base.html" %}
{% block base %}
index template
{% endblock %}