CloudSave/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from cloud_azure import urls as azure_urls
from base import  urls as base_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'azure/', include(azure_urls,namespace='azure')),
    path(r'', include(base_urls, namespace='base')),
]

base/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
app_name = "instances"
urlpatterns = [
    # path("", views.index, name='index'),
    path("", views.index, name='home' ),
]

cloud_azure/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = "instances"
urlpatterns = [
    # path("", views.index, name='index'),
    path("home/", views.index, name='home'),
    path("azure/", views.azure, name='azure'),
    path("vm/deallocated/<str:timefilter>", views.getDeallocatedInstances,name='deallocated'),
    path("vm/deallocated/", views.getDeallocatedInstances,name='deallocated'),
    # path("vms2/", views.vms2,name='vms2'),
    path("disks/", views.index, name='disks'),
    path("blob/", views.index, name='blob'),
    # path("collect/", views.collectVmsFromAzure,name='collect'),
    path("vm/tags/", views.tags, name='tags'),
    path("vm/tags/<str:timefilter>", views.tags, name='tags'),
    # path("tags/",views.getTags, name='tags')
    # path("vm/deallocated", views.deallocated, name='deallocated'),
    path("backup/", views.backup,name = 'backup'),
]

base/views.py
from django.shortcuts import render
import datetime
title = "Azuremon"
menu = {}
menu = {
    "home": "HOME",
    "vms": "Virtual Machines",
    "disks": "Disks",
    "blob":  "Blob",
    "collect": "Collect data"}
now = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
# Create your views here.
def index(request):
    return render(request, 'index.html', {"active":"home","menu": menu,'title':title, 'data':now})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <title>{{ title }}</title>
    <!--<link rel="stylesheet" href="{% static 'css/menu.css' %}">-->
</head>

<meta name="viewport" content="width=device-width, initial-scale=1"></meta>
<meta name="mobile-web-app-capable" content="yes">
<meta charset="UTF-8">
<body>
{#base.html#}
<br>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/limenu.cssbs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
      integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
{#<nav class="navbar navbar-expand-lg navbar-light bg-light">#}
<nav class="navbar navbar-expand-sm  navbar-light" style="background-color: #b7defa;">
    <a class="navbar-brand" href="{% url 'base:home' %}">{{ title }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'azure:azure' %}">Azure <span
                    class="sr-only">(current)</span></a>
            <a class="nav-item nav-link disabled" href="#" data-toggle="tooltip" data-placement="top" title="Not Available">AWS</a>
            <a class="nav-item nav-link disabled" href="#" data-toggle="tooltip" data-placement="top" title="Not Available">GPC</a>
            <a class="nav-item nav-link disabled" href="#" data-toggle="tooltip" data-placement="top" title="Not Available" >ActionPoint</a>
        </div>
    </div>
</nav>
{% autoescape off %}
    {% block menu %}
    {% endblock %}
    {% block base %}
    {% endblock %}
    {% block azure %}
    {% endblock %}
{% endautoescape %}

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block base %}
    {{ data }} <br>
{% endblock %}